project_id = "oypsdwgvjwycgjxfqndi"

[functions.rabbit-hole-step]
verify_jwt = false

[functions.panel-step]
verify_jwt = false

[functions.grounding-panel-step]
verify_jwt = false

[functions.backfill-embeddings]
verify_jwt = false

[functions.brilliance-compression-engine]
verify_jwt = false

[functions.atom-status-engine]
verify_jwt = false